# Spam Classification Configuration

# Data
data:
  dataset_path: "data/sms_spam_no_header.csv"
  test_size: 0.2
  random_state: 42
  
# Preprocessing
preprocessing:
  lowercase: true
  remove_punctuation: true
  remove_stopwords: true
  max_features: 5000  # TF-IDF max features
  min_df: 2           # Minimum document frequency
  max_df: 0.95        # Maximum document frequency
  
# Models
models:
  logistic_regression:
    C: 1.0
    max_iter: 1000
    random_state: 42
    
  naive_bayes:
    alpha: 1.0
    
  svm:
    C: 1.0
    kernel: "linear"
    random_state: 42

# Output
output:
  models_dir: "models"
  outputs_dir: "outputs"
  
# Visualization
visualization:
  figsize: [10, 8]
  dpi: 100
  style: "seaborn-v0_8"
